# Generated by Django 2.1.7 on 2019-03-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('runtime', models.PositiveSmallIntegerField(verbose_name='Runtime in minutes')),
                ('genre', models.CharField(max_length=65)),
                ('director', models.CharField(max_length=65)),
                ('country', models.CharField(max_length=65)),
            ],
        ),
    ]
