version: '3'

services:
  db:
    image: postgres
    hostname: db

  mapi:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: mAPI
    volumes:
      - .:/mAPI
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx
    hostname: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - mapi
